"""tabelas do sistema

Revision ID: 364dc22059f6
Revises: 
Create Date: 2026-09-10 20:28:10.552436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '364dc22059f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_nome'), 'categorias', ['nome'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.Enum('administrador', 'gerente', 'tecnico', 'visualizador', name='cargo_usuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('equipamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_aquisicao', sa.Date(), nullable=False),
    sa.Column('patrimonio', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('id_responsavel', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['id_responsavel'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipamentos_id_categoria'), 'equipamentos', ['id_categoria'], unique=False)
    op.create_index(op.f('ix_equipamentos_id_responsavel'), 'equipamentos', ['id_responsavel'], unique=False)
    op.create_index(op.f('ix_equipamentos_patrimonio'), 'equipamentos', ['patrimonio'], unique=True)
    op.create_table('manutencoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_equipamento', sa.Integer(), nullable=False),
    sa.Column('id_responsavel', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('custo', sa.Float(), nullable=False),
    sa.Column('data_abertura', sa.Date(), nullable=False),
    sa.Column('data_conclusao', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_equipamento'], ['equipamentos.id'], ),
    sa.ForeignKeyConstraint(['id_responsavel'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manutencoes_id_equipamento'), 'manutencoes', ['id_equipamento'], unique=False)
    op.create_index(op.f('ix_manutencoes_id_responsavel'), 'manutencoes', ['id_responsavel'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manutencoes_id_responsavel'), table_name='manutencoes')
    op.drop_index(op.f('ix_manutencoes_id_equipamento'), table_name='manutencoes')
    op.drop_table('manutencoes')
    op.drop_index(op.f('ix_equipamentos_patrimonio'), table_name='equipamentos')
    op.drop_index(op.f('ix_equipamentos_id_responsavel'), table_name='equipamentos')
    op.drop_index(op.f('ix_equipamentos_id_categoria'), table_name='equipamentos')
    op.drop_table('equipamentos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_categorias_nome'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
