/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroUsuarioRouteImport } from './routes/cadastro-usuario'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as EquipamentosIndexRouteImport } from './routes/equipamentos.index'
import { Route as EquipamentosNovoRouteImport } from './routes/equipamentos.novo'
import { Route as ManutencoesIndexRouteImport } from './routes/manutencoes.index'
import { Route as ManutencoesNovaRouteImport } from './routes/manutencoes.nova'
import { Route as EquipamentosIdIndexRouteImport } from './routes/equipamentos.$id.index'
import { Route as EquipamentosIdEditarRouteImport } from './routes/equipamentos.$id.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroUsuarioRoute = CadastroUsuarioRouteImport.update({
  id: '/cadastro-usuario',
  path: '/cadastro-usuario',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosIndexRoute = EquipamentosIndexRouteImport.update({
  id: '/equipamentos/',
  path: '/equipamentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosNovoRoute = EquipamentosNovoRouteImport.update({
  id: '/equipamentos/novo',
  path: '/equipamentos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencoesIndexRoute = ManutencoesIndexRouteImport.update({
  id: '/manutencoes/',
  path: '/manutencoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencoesNovaRoute = ManutencoesNovaRouteImport.update({
  id: '/manutencoes/nova',
  path: '/manutencoes/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosIdIndexRoute = EquipamentosIdIndexRouteImport.update({
  id: '/equipamentos/$id/',
  path: '/equipamentos/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosIdEditarRoute = EquipamentosIdEditarRouteImport.update({
  id: '/equipamentos/$id/editar',
  path: '/equipamentos/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro-usuario': typeof CadastroUsuarioRoute
  '/inicio': typeof InicioRoute
  '/equipamentos/novo': typeof EquipamentosNovoRoute
  '/manutencoes/nova': typeof ManutencoesNovaRoute
  '/equipamentos/': typeof EquipamentosIndexRoute
  '/manutencoes/': typeof ManutencoesIndexRoute
  '/equipamentos/$id/editar': typeof EquipamentosIdEditarRoute
  '/equipamentos/$id/': typeof EquipamentosIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro-usuario': typeof CadastroUsuarioRoute
  '/inicio': typeof InicioRoute
  '/equipamentos/novo': typeof EquipamentosNovoRoute
  '/manutencoes/nova': typeof ManutencoesNovaRoute
  '/equipamentos': typeof EquipamentosIndexRoute
  '/manutencoes': typeof ManutencoesIndexRoute
  '/equipamentos/$id/editar': typeof EquipamentosIdEditarRoute
  '/equipamentos/$id': typeof EquipamentosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro-usuario': typeof CadastroUsuarioRoute
  '/inicio': typeof InicioRoute
  '/equipamentos/novo': typeof EquipamentosNovoRoute
  '/manutencoes/nova': typeof ManutencoesNovaRoute
  '/equipamentos/': typeof EquipamentosIndexRoute
  '/manutencoes/': typeof ManutencoesIndexRoute
  '/equipamentos/$id/editar': typeof EquipamentosIdEditarRoute
  '/equipamentos/$id/': typeof EquipamentosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro-usuario'
    | '/inicio'
    | '/equipamentos/novo'
    | '/manutencoes/nova'
    | '/equipamentos/'
    | '/manutencoes/'
    | '/equipamentos/$id/editar'
    | '/equipamentos/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro-usuario'
    | '/inicio'
    | '/equipamentos/novo'
    | '/manutencoes/nova'
    | '/equipamentos'
    | '/manutencoes'
    | '/equipamentos/$id/editar'
    | '/equipamentos/$id'
  id:
    | '__root__'
    | '/'
    | '/cadastro-usuario'
    | '/inicio'
    | '/equipamentos/novo'
    | '/manutencoes/nova'
    | '/equipamentos/'
    | '/manutencoes/'
    | '/equipamentos/$id/editar'
    | '/equipamentos/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroUsuarioRoute: typeof CadastroUsuarioRoute
  InicioRoute: typeof InicioRoute
  EquipamentosNovoRoute: typeof EquipamentosNovoRoute
  ManutencoesNovaRoute: typeof ManutencoesNovaRoute
  EquipamentosIndexRoute: typeof EquipamentosIndexRoute
  ManutencoesIndexRoute: typeof ManutencoesIndexRoute
  EquipamentosIdEditarRoute: typeof EquipamentosIdEditarRoute
  EquipamentosIdIndexRoute: typeof EquipamentosIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-usuario': {
      id: '/cadastro-usuario'
      path: '/cadastro-usuario'
      fullPath: '/cadastro-usuario'
      preLoaderRoute: typeof CadastroUsuarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos/': {
      id: '/equipamentos/'
      path: '/equipamentos'
      fullPath: '/equipamentos/'
      preLoaderRoute: typeof EquipamentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos/novo': {
      id: '/equipamentos/novo'
      path: '/equipamentos/novo'
      fullPath: '/equipamentos/novo'
      preLoaderRoute: typeof EquipamentosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencoes/': {
      id: '/manutencoes/'
      path: '/manutencoes'
      fullPath: '/manutencoes/'
      preLoaderRoute: typeof ManutencoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencoes/nova': {
      id: '/manutencoes/nova'
      path: '/manutencoes/nova'
      fullPath: '/manutencoes/nova'
      preLoaderRoute: typeof ManutencoesNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos/$id/': {
      id: '/equipamentos/$id/'
      path: '/equipamentos/$id'
      fullPath: '/equipamentos/$id/'
      preLoaderRoute: typeof EquipamentosIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos/$id/editar': {
      id: '/equipamentos/$id/editar'
      path: '/equipamentos/$id/editar'
      fullPath: '/equipamentos/$id/editar'
      preLoaderRoute: typeof EquipamentosIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroUsuarioRoute: CadastroUsuarioRoute,
  InicioRoute: InicioRoute,
  EquipamentosNovoRoute: EquipamentosNovoRoute,
  ManutencoesNovaRoute: ManutencoesNovaRoute,
  EquipamentosIndexRoute: EquipamentosIndexRoute,
  ManutencoesIndexRoute: ManutencoesIndexRoute,
  EquipamentosIdEditarRoute: EquipamentosIdEditarRoute,
  EquipamentosIdIndexRoute: EquipamentosIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
