/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroUsuarioRouteImport } from './routes/cadastro-usuario'
import { Route as EquipamentosIndexRouteImport } from './routes/equipamentos.index'
import { Route as EquipamentosNovoRouteImport } from './routes/equipamentos.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroUsuarioRoute = CadastroUsuarioRouteImport.update({
  id: '/cadastro-usuario',
  path: '/cadastro-usuario',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosIndexRoute = EquipamentosIndexRouteImport.update({
  id: '/equipamentos/',
  path: '/equipamentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosNovoRoute = EquipamentosNovoRouteImport.update({
  id: '/equipamentos/novo',
  path: '/equipamentos/novo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro-usuario': typeof CadastroUsuarioRoute
  '/equipamentos/novo': typeof EquipamentosNovoRoute
  '/equipamentos/': typeof EquipamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro-usuario': typeof CadastroUsuarioRoute
  '/equipamentos/novo': typeof EquipamentosNovoRoute
  '/equipamentos': typeof EquipamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro-usuario': typeof CadastroUsuarioRoute
  '/equipamentos/novo': typeof EquipamentosNovoRoute
  '/equipamentos/': typeof EquipamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cadastro-usuario' | '/equipamentos/novo' | '/equipamentos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cadastro-usuario' | '/equipamentos/novo' | '/equipamentos'
  id:
    | '__root__'
    | '/'
    | '/cadastro-usuario'
    | '/equipamentos/novo'
    | '/equipamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroUsuarioRoute: typeof CadastroUsuarioRoute
  EquipamentosNovoRoute: typeof EquipamentosNovoRoute
  EquipamentosIndexRoute: typeof EquipamentosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-usuario': {
      id: '/cadastro-usuario'
      path: '/cadastro-usuario'
      fullPath: '/cadastro-usuario'
      preLoaderRoute: typeof CadastroUsuarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos/': {
      id: '/equipamentos/'
      path: '/equipamentos'
      fullPath: '/equipamentos/'
      preLoaderRoute: typeof EquipamentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos/novo': {
      id: '/equipamentos/novo'
      path: '/equipamentos/novo'
      fullPath: '/equipamentos/novo'
      preLoaderRoute: typeof EquipamentosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroUsuarioRoute: CadastroUsuarioRoute,
  EquipamentosNovoRoute: EquipamentosNovoRoute,
  EquipamentosIndexRoute: EquipamentosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
